In [49]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [50]:
data = pd.read_csv('Real estate.csv')

In [51]:
data.head(10)

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   
5   6             2012.667           7.1   
6   7             2012.667          34.5   
7   8             2013.417          20.3   
8   9             2013.500          31.7   
9  10             2013.417          17.9   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   
5                              2175.03000                                3   
6                               623.47310                                7   
7                               287.60250                                6   
8                              5512.03800                                1   
9                              1783.18000                                3   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1  
5     24.96305     121.51254                        32.1  
6     24.97933     121.53642                        40.3  
7     24.98042     121.54228                        46.7  
8     24.95095     121.48458                        18.8  
9     24.96731     121.51486                        22.1

In [52]:
print(data[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']])

     X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..             

In [54]:
reg1 = linear_model.LinearRegression()
reg1.fit(data[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']],data[['Y house price of unit area']])

LinearRegression()

In [55]:
reg1.coef_

array([[ 5.14622746e+00, -2.69695448e-01, -4.48746107e-03,
         1.13327690e+00,  2.25472976e+02, -1.24236012e+01]])

In [56]:
reg1.intercept_

array([-14437.10080228])

In [57]:
reg.predict([[2012.917,32,84.87,10,24.98,121.54]])

array([[46.50005068]])